# Generated by Django 3.2.8 on 2021-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('info', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'en_car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kcar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('info', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'kcar',
                'managed': False,
            },
        ),
    ]
