# Generated by Django 3.2.8 on 2021-10-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'search',
                'managed': False,
            },
        ),
    ]
